title: Tommy Truong
logo: images/pfp.png
description: Hello, welcome to my portfolio! Here you will find a range of data analytics projects that I have completed. Please feel free to take a look around.
#show_downloads: false 
theme: jekyll-theme-minimal
